# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Install packages
      run: sudo -E apt -y install libgtk-3-dev libgirepository1.0-dev
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate sources
      run: ./gradlew generator:generate
    - name: Generate JNI headers
      run: ./gradlew library:classes
    - name: Compile C code
      run: make -C glue -j 3
    - name: Build library
      run: ./gradlew library:build
    - name: Build exsamples
      run: ./gradlew examples:build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: java-gtk
        path: library/build/libs/*
        if-no-files-found: error
